### ISSUE TITLE
get_elevation not working under Windows

### ISSUE THREAD

**Issue by Axel2** [tkrajina/geoelevations#2]
Hi Tomo,
I'm not sure, if it's really an issue or if I use the wrong zip-gem. For getting it working, I had to change 3 lines regarding zip:

OLD:
require 'zip/zip'
..
 Zip::ZipFile.open(temp_file) do |zip_file|
..

NEW:
require 'zip'
..
temp_file.binmode
..
Zip::File.open(temp_file) do |zip_file|

You can find it here:
https://github.com/Axel2/geoelevations

In my gems, I have:
- rubyzip (1.2.0)
- rubyzip2 (2.0.2)

I'm using ruby 1.9.3p448 (2013-06-27) [i386-mingw32] on Windows 8.1.

Kind Regards,
Axel

**Comment by tkrajina** [comment]
Unfortunately I don't have the time to maintain this repo. If somebody is willing to maintain it -- I'm here.
